// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeAgkAAwRlgDE950uX2YZDyGSowqXiWTw',
    appId: '1:529516984613:web:7d9e420b6881ce9819c2cc',
    messagingSenderId: '529516984613',
    projectId: 'secondapp-5f744',
    authDomain: 'secondapp-5f744.firebaseapp.com',
    storageBucket: 'secondapp-5f744.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJF1pg19cQjtzfhPfdD5VJbvNFN5jf-U0',
    appId: '1:529516984613:android:5140f5d2edffc30319c2cc',
    messagingSenderId: '529516984613',
    projectId: 'secondapp-5f744',
    storageBucket: 'secondapp-5f744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-EHmwhc0bTtO6a96i1bTb8K1hliMjHc',
    appId: '1:529516984613:ios:c972bd9b9bb5897919c2cc',
    messagingSenderId: '529516984613',
    projectId: 'secondapp-5f744',
    storageBucket: 'secondapp-5f744.firebasestorage.app',
    iosBundleId: 'com.example.nafakaMakert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-EHmwhc0bTtO6a96i1bTb8K1hliMjHc',
    appId: '1:529516984613:ios:c972bd9b9bb5897919c2cc',
    messagingSenderId: '529516984613',
    projectId: 'secondapp-5f744',
    storageBucket: 'secondapp-5f744.firebasestorage.app',
    iosBundleId: 'com.example.nafakaMakert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeAgkAAwRlgDE950uX2YZDyGSowqXiWTw',
    appId: '1:529516984613:web:4ae9b0bbd3938a3c19c2cc',
    messagingSenderId: '529516984613',
    projectId: 'secondapp-5f744',
    authDomain: 'secondapp-5f744.firebaseapp.com',
    storageBucket: 'secondapp-5f744.firebasestorage.app',
  );
}
